#!/bin/bash
# Put this file in the folder /etc/cron.hourly
# Do not add a file extension to this file

cd /congress-forms
source /home/ubuntu/.rvm/environments/ruby-2.1.0@congress-forms

bundle exec rake congress-forms:clone_git[]

rm -rf /tmp/contact-congress